name: Maptime AMS
baseurl:

animation-interval: 5500
building-stroke-width: 8

venue: TomTom, Oosterdoksstraat 114, 1011 DK Amsterdam
venue-url: "https://www.openstreetmap.org/node/10058517320"

links:
  - title: Maptime HQ 
    url: http://maptime.io/

  - title: Meetup
    url: http://www.meetup.com/Maptime-AMS

  - title: Twitter
    url: https://twitter.com/MaptimeAMS

  - title: GitHub
    url: https://github.com/maptime-ams

  - title: TM Systems | TomTom
    url: https://www.tmspl.com/

  - title: TomTom
    url: https://www.tomtom.com/

collections:
  meetups:
    output: true
    permalink: /meetups/:path/

defaults:
  - scope:
      path: meetups
    values:
      layout: presentation
